### ISSUE TITLE
GeoJSON cache and tiles

### ISSUE THREAD

**Issue by lennerd** [sozialhelden/wheelmap#27]
Regarding #18:

# Implement GeoJSON Cache and Tiles

A elasticsearch based GeoJSON cache synced with our MySQL database could speed up the node requests enormously.

The Wheelmap also has problems with clustering in that we don't have clusters yet.

<img width="1072" alt="screenshot 2015-09-28 08 25 54" src="https://cloud.githubusercontent.com/assets/1609692/10133843/018df0c0-65e1-11e5-881c-0d509064edd1.png">

Especially in lower zoom levels, the map is only filled with nodes irregularly. We use a limit of 300 nodes per bounding box requests which is not enough to fill the whole map.

Plan is to implement a GeoJSON cache/tile storage powered by ElasticSearch which gets filled with data from the MySQL database.

What are GeoJSON tiles: They allow us to load nodes in predefined areas for a specific zoom level and bounding box and cache the response accordingly.

*The biggest problems in implementing GeoJSON tiles is I think the frontend and the filter features provided by the toolbar.* In the current Ember implementation, all nodes are loaded regardless their accessibility and toilet status. This way the frontend application can filter the nodes on the client and give instant feedback.
To achieve this, we need a way to reload cluster tiles if their number of nodes drops below a certain number and the other way round if all filters are deactivated–or maybe different, open for discussion this is. 

## Todos:

- [ ] Implement ElasticSearch as GeoJSON cache getting synced with the MySQL database
- [x] Implement GeoJSON tiles into the backend (partly done as draft serving nodes from the MySQL database)
- [x] Implement GeoJSON tiles in the frontend app (#23 is maybe blocking this)

**Comment by lennerd** [comment]
So this already working and implemented with our rails app. It's worth mentioning that we don't have any clusters yet (I'm not quite sure, if we need them), but a early and great working version of GeoJSON tiles.

Most important next step is ElasicSearch as the tiles provider I think.

**Comment by holgerd** [comment]
@lennerd can this be closed?
