### ISSUE TITLE
Export POI data as CSV-file from the backend for Streetspotr

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#433]
For the new project with our crowdsourcing partner Streetspotr http://news.wheelmap.org/streetspotr-brechen-alle-rekorde-28-000-bilder-gesammelt/ we need an export of specific POI data into a csv-file.

**The cities where those POIs are located are:**
Italy: Mailand, Rom, Neapel
Spain: Madrid, Barcelona, Valencia
France: Paris, Marseille, Lyon
UK: London, Birmingham, Glasgow
Finland: Helsinki, Tampere, Turku
Denmark: Kopenhagen, Aarhus, Odense
Sweden: Stockholm, Göteborg (Goeteborg?), Malmö (Malmoe?)
Netherlands: Amsterdam, Rotterdam, Den Haag
Belgien: Antwerpen, Charleroi, Brüssel (Bruessel?)
Irland: Dublin, Cork, Galway
Russia: Moskau, Sankt Petersburg, Nowosibirsk
Rumänien: Bukarest, Klausenburg, Temeswar

Deutschland (the 20 biggest cities): Berlin, Hamburg, Muenchen, Koeln, Frankfurt am Main, Stuttgart, Duesseldorf, Dortmund, Essen, Leipzig, Bremen, Dresden, Hannover, Nuernberg, Duisburg, Bochum, Wuppertal, Bielefeld, Bonn, Münster (sic! Here the "Umlaut" is available.)
1. Svenja has checked which cities are not available as regions in the backend. The following need to be imported into our backend first:
   https://docs.google.com/spreadsheets/d/13VpThehPWJ-y_ZdoXMKw3UVnsJ8PrrIPblR6bd0jpkQ/edit?usp=sharing 
2. @holgerd is trying to get the currently missing, necessary WKT-files for the shapes of the cities and upload them here when available.
3. These WKT-files need to be implemented into our backend.
4. After new regions have been defined in the backend, we need an export of POI-data in a csv format. Each country should have an own sheet with the data of the 3 (or for Germany: 20) cities. Example: The CSV file for Italy should contain all POIs of the needed categories, accessibility status and photo parameter for Mailand, Rom and Neapel.

As I just checked, I cannot do an export using the UI of the current backend because the filter settings are not working for creating a corresponding csv sheet (see: https://github.com/sozialhelden/wheelmap/issues/432)
@christoph-buente had a certain Script for that which should be documented.
@1000miles: Could you look that up, clarify with Christoph if necessary and do the export?

The parameters of the export (apart from the cities)
- unknown accessibility
- has no photo
- categories: food, shopping, leisure, tourism (excluding the node type: memorial)

Experiences from the last exports running on Christoph's script:
- Be careful to use the city names as stored in the backend. In the past we forgot about the "Umlaut" issue, those POI entries where not exported.
- The node type "memorial" must be excluded from the category tourism in the export because tons of "Stolpersteine", a special memorial marking the deportation of jews in the 2nd World War, dominated the memorial data. It does not make sense to have pictures taken of them within the streetspotr activity.

**Comment by holgerd** [comment]
Here are the first 29 WKT files, the russian ones are still missing and will be added later:
[29 WKTs.zip](https://github.com/sozialhelden/wheelmap/files/526714/29.WKTs.zip)

**Comment by 1000miles** [comment]
Thanks, @Svenyo & @holgerd 

Can you please put this ticket into a milestone and set a date along with all other issues that needs to be done? Then we can better estimate the tasks if and to when the issues can be done. Merci.

**Comment by holgerd** [comment]
Updated WKT folder zip:
[32_WKTs_lowercase_no_space_no_umlauts.zip](https://github.com/sozialhelden/wheelmap/files/526881/32_WKTs_lowercase_no_space_no_umlauts.zip)

**Comment by 1000miles** [comment]
Thanks for creating this issue, @Svenyo 

**Tasks to do for us:**
- [ ] 0. Get complete wkt files from @holgerd & @svenyo to import before start
- [ ] I. Fix Filter settings of "POI" view are not included in the csv export #432
- [ ] II. Import new regions listed in this GoogleSheet: https://docs.google.com/spreadsheets/d/13VpThehPWJ-y_ZdoXMKw3UVnsJ8PrrIPblR6bd0jpkQ/edit#gid=1993880246
- [ ] III. Export csv file with data from following countries/cities:

       **(y) = yes, wkt file already imported**
       **(n) = no, wkt file not imported**

   - [ ] Italy: Mailand (n) , Rom (n) , Neapel (n)  
   - [ ] Spain: Madrid (y) , Barcelona (n) , Valencia (n) 
   - [ ] France: Paris (y) , Marseille (n) , Lyon (n) 
   - [ ] UK: London (y) , Birmingham (n) , Glasgow (n) 
   - [ ] Finland: Helsinki (n) , Tampere (n) , Turku (n) 
   - [ ] Denmark: Kopenhagen (n) , Aarhus (n) , Odense (n) 
   - [ ] Sweden: Stockholm (n) , Göteborg (Goeteborg?) (n) , Malmö (Malmoe?) (n) 
   - [ ] Netherlands: Amsterdam (n) , Rotterdam (n) , Den Haag (n) 
   - [ ] Belgien: Antwerpen (n) , Charleroi (n) , Brüssel (Bruessel?) (n) 
   - [ ] Irland: Dublin(y) , Cork (n) , Galway (n) 
   - [ ] Russia: Moskau (n) , Sankt Petersburg (n) , Nowosibirsk (n) 
   - [ ] Rumänien: Bukarest (n) , Klausenburg (n) , Temeswar (n) 
   - [ ] Deutschland (the 20 biggest cities): Berlin (y) , Hamburg (y) , Muenchen (y) , Koeln (y) , Frankfurt am Main (y) ,  Stuttgart (y) , Duesseldorf (y) , Dortmund (y) , Essen (y) , Leipzig (y) , Bremen (y) , Dresden (y) , Hannover (y) , Nuernberg (y) , Duisburg (y) , Bochum (y) , Wuppertal (y) , Bielefeld (y) , Bonn (y) , 
   - [ ] Münster (sic! Here the "Umlaut" is available.)  (y) **Consider issue https://github.com/sozialhelden/wheelmap/issues/82** 

   **with following parameters:**

   - [ ] unknown accessibility
   - [ ] has no photo
   - [ ] categories: food, shopping, leisure, tourism **(excluding the node type: memorial)**

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

Svenja, you wrote in the initial post that Birmingham and Rom should be exported too but I realized that neither the Google Sheet nor the wkt file currently exists in our database. 

Can you please confirm that these 2 cities don't need to be imported? If they need to be imported, we need the 2 missing wkt-files from you. Merci. :)

Missing:
  - [ ] Rom
  - [ ] Birmingham

**Comment by Svenyo** [comment]
Hmm, that's strange, I can see the entries of both cities in our backend.

@holgerd: Could you also look up the wkt-files for 

- [ ] Birmingham, OSM relation ID 162378
- [ ] Rom, OSM relation ID 41485

**Comment by 1000miles** [comment]
Oh, I am sorry. You are right, I found the 2 cities now in the second run.

**Comment by 1000miles** [comment]
@Svenyo But do you still need an export of these 2 cities even though they are not listed in the Google Sheet?

**Comment by Svenyo** [comment]
@1000miles Yes, as listed in my initial post with the three biggest cities. The Google sheet you refer to was basically meant as an overview of the missing wkt-files for @holgerd.

**Comment by Svenyo** [comment]
By the way, @1000miles I just recognized I made a mistake with the categories.
Please cancel "Leisure" and put "accomodation" instead -->

- [ ] categories: food, shopping, accomodation, tourism (excluding the node type: memorial)

And: The amount of POIs exported for each category can be limited to 1000. Like this, for each city we'd have a data sheet of 4000 grey POIs.

**Comment by 1000miles** [comment]
@Svenyo Ok, thanks.

**Comment by 1000miles** [comment]
Getting error messages while importing the wkt-files on the staging server. Will remove the corrupt files to continue the import first and list the corrupt file names here later.

``
Importing Kopenhagen
rake aborted!
ActiveRecord::RecordInvalid: Gültigkeitsprüfung ist fehlgeschlagen: Grenze muss ausgefüllt werden
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/validations.rb:57:in `save!'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/transactions.rb:273:in `block in save!'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/transactions.rb:208:in `transaction'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/activerecord-4.1.15/lib/active_record/transactions.rb:273:in `save!'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:34:in `block in save!'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent.rb:574:in `with_database_metric_name'
/var/apps/wheelmap/staging/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/active_record_helper.rb:33:in `save!'
/var/apps/wheelmap/staging/releases/20161014114858/app/models/region.rb:46:in `from_wkt_file'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:94:in `block in import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `each'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:97:in `block in import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `each'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:97:in `block in import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `each'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:65:in `import_region'
/var/apps/wheelmap/staging/releases/20161014114858/lib/tasks/region.rake:60:in `block (2 levels) in <top (required)>'
Tasks: TOP => region:import
(See full trace by running task with --trace)
```

**Comment by 1000miles** [comment]
@Svenyo & @holgerd 

Great, it seems only the [Kopenhagen.wkt](https://github.com/sozialhelden/wheelmap/commit/f42a62930661b3dc956c725c1a7b56b5a25753d5) file is corrupt. Could you please re-check what is wrong with this file (maybe the polygon borders are not correct) and maybe create another one? 

We have imported the rest of cities successfully on the staging today. 

You can check them here on staging:
https://staging.wheelmap.org/admin/regions?utf8=%E2%9C%93&q%5Bcreated_at_gteq%5D=2016-10-14&commit=Filtern&order=id_desc

**Comment by 1000miles** [comment]
ping @Svenyo & @holgerd 

Any news regarding the `Kopenhagen.wkt` file here? Pls see comment: https://github.com/sozialhelden/wheelmap/issues/433#issuecomment-253791192

**Comment by Svenyo** [comment]
@holgerd Do you see any alternative to using http://www.openstreetmap.org/relation/2192363  ? Maybe using the "Capital Region of Denmark" admin level 4: http://www.openstreetmap.org/relation/1320608 ?

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd 

We saw that there is already a [rake task runner for streetspotr](https://github.com/sozialhelden/wheelmap/blob/8df541107ed785f82a2436ebe53d11129e7e2fba/lib/tasks/export.rake#L170-L210) to export csv, so we are wondering if we should create an additional rake task with the given parameters you requested above but we need to know if the current parameters from you are just requested one-time or will repeat in the future?

- [ ] unknown accessibility
- [ ] has no photo
- [ ] categories: food, shopping, accommodation, tourism (excluding the node type: memorial)

**Comment by Svenyo** [comment]
@1000miles Yes, we will need this request with the exact parameters in future for other countries/ regions/ cities.

**Comment by holgerd** [comment]
I re-exported copenhagen using http://polygons.openstreetmap.fr/index.py?id=2192363 and the relation http://ra.osmsurround.org/analyzeRelation?relationId=2192363&_noCache=on

[kopenhagen.wkt.zip](https://github.com/sozialhelden/wheelmap/files/535968/kopenhagen.wkt.zip)

**Comment by 1000miles** [comment]
@holgerd cc @svenyo Unfortunately the new `Kopenhagen.wkt` file did not work either. Looking at the link you provided (http://ra.osmsurround.org/analyzeRelation?relationId=2192363&_noCache=on) the relation_name is `Københavns Kommune`. Is that the correct one?

**Comment by Svenyo** [comment]
@holgerd The new relation ID we need an WKT file from is http://www.openstreetmap.org/relation/1320608 named "Capital region of Denmark" as an alternative for the old one which is broken "Kobenhavn Kommune", ID 2192363. So You've downloaded the former broken one once again. 

Please let's try with the WKT-file for http://www.openstreetmap.org/relation/1320608.

**Comment by holgerd** [comment]
[kopenhagen-0-1320608.wkt.zip](https://github.com/sozialhelden/wheelmap/files/536593/kopenhagen-0-1320608.wkt.zip)

better?

**Comment by 1000miles** [comment]
Thank you, @Svenyo & @holgerd 

Already replaced it in this commit 225ed10243be2f6c8707c7cc3edcf922ee30f5ff => import finally worked on staging, so we can merge this PR https://github.com/sozialhelden/wheelmap/pull/438 tomorrow and deploy all new regions to production after approval. :)

**Comment by 1000miles** [comment]
**Update, 25 Oct 2016:**

As agreed with @holgerd and @Svenyo today we will do the csv export without the param `has no photo` since this query (check if a poi has any photos) takes a lot of time to execute.

**Comment by 1000miles** [comment]
**Update, 27 Oct 2016:**

#Done
- import 31 new regions - PR #438 
- create new rake task for `bundle exec rake export:for_streetspotr_no_photo_no_memorial` - PR #453
- fix broken rake task `bundle exec rake poi:locate`  - PR #462 
- fix broken poi table in the mysql database  (Error: `Mysql2::Error: Incorrect key file for table './wheelmap_production/pois.MYI'; try to repair it`)
- part I: deliver csv file for Germany (20 regions) on 26 Oct 2016
- part II: deliver csv file for rest (12 countries with 36 regions) on 28 Oct 2016

**Comment by 1000miles** [comment]
As this is done, I am closing this ticket. :)
