### ISSUE TITLE
[DB] Import node/ways from osm to wheelmap DB

### ISSUE THREAD

**Issue by 1000miles** [sozialhelden/wheelmap#493]
After the introduction of 27 new node types (2016-11-29) we expected to see a significant increase of pois (that are marked under these node types) on wheelmap.org, instead only a small amount was synced from osm to wheelmap. 

According to our checks the osm sync works fine for every poi that was created  *after* our introduction of new node types but those that were created/edited before (e.g. 1 month) do not appear on wheelmap.org. Now we need to import the missing nodes/ways from openstreetmap to wheelmap manually.

**Tasks to be done:**
- [x] Download planet dump from geofabrik
- [x] Filter attributes and export to a separate osm file
- [x] Import osm file with nodes/ways into the data base
