### ISSUE TITLE
Add/Update place types (key/value-pairs) = categories

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#54]
Some place types are used in OpenStreetMap but can not be used in Wheelmap until now. Some have changed.
- [ ] Add the key/value types described in this public google spreadsheet with wheelmap-category and Icon (as linked in spreadsheet). @christoph-buente has done this several times before, there should be something already. Spreadsheet attached and here: 

https://docs.google.com/spreadsheets/d/12yuBoD8HNaC0sMH3JgLQlImz8NOMcaYgY0kRQpMDlSQ/edit?usp=sharing

[Neue Ortstypen für die Wheelmap.xlsx](https://github.com/sozialhelden/wheelmap/files/27384/Neue.Ortstypen.fur.die.Wheelmap.xlsx)

**Comment by holgerd** [comment]
scraper info for wheelmap.org
https://www.dropbox.com/s/qlbti2ksgi4hoxj/wheelmapohnemap.html?dl=0

scraper info for wheelmap.org/map
https://www.dropbox.com/s/eb12nft1fol0yvq/wheelmapMITmap.html?dl=0

**Comment by holgerd** [comment]
url to download the copied HTML of scraper info:
https://www.dropbox.com/sh/cmkqqbzn4732lgv/AAB2yz8DBsqzfAf-W7FVA7ria?dl=0

**Comment by holgerd** [comment]
Related to this there is a suggestion from OSM users https://lists.openstreetmap.org/pipermail/talk-de/2015-November/112250.html

- [ ] Make it possible to NOT show places with this combination: leisure=swimming_pool + access=private

**Comment by lennerd** [comment]
Everything is nearly prepared. There is one bigger step missing: the icon sprite file.

All our apps (iPhone, Android and Windows Phone) are using this file to show icons on the markers. If we add icons to this spirte, the position of the icons inside the sprite will change. As all the apps are propably are hardcoding the icon positions, it would break the icons representation.

So we need a smarter way to add new icons and also be sure that our mobile apps are capable of displaying them. Maybe we can add information to our API. Open for discussion this is.

**Comment by christoph-buente** [comment]
From what i know: There is no sprite file, but a zip file with alle the markers in it.

**Comment by lennerd** [comment]
Yes, but I'm not sure, if the Android and iPhone are still using them. The Windows Phone App is using the sprite file though.

**Comment by christoph-buente** [comment]
What sprite? This is not delivered by the api anyways

**Comment by lennerd** [comment]
As far as I know, they use the sprite file from the application.

**Comment by christoph-buente** [comment]
Where is this file, who created it, is it in version control?

**Comment by christoph-buente** [comment]
I think api clients fetch the icons per node type from the api

{
      "id":23,
      "identifier":"hardware",
      "icon":"/images/icons/wrench.png",
      "localized_name":"Eisenwarenladen",
      "category":{
        "id": 1,
        "identifier": "shopping"
      }

**Comment by lennerd** [comment]
It's the same file we use for our icons. https://github.com/sozialhelden/wheelmap/blob/master/public/icons/icon-sprite.png

**Comment by lennerd** [comment]
The Windows Phone App is pretty new. As I said, I'm not absoluty sure about this.

**Comment by christoph-buente** [comment]
I'm pretty sure, this file is not exposed by the api. If windows phone is using it, some one gave it to the developers ...

**Comment by lennerd** [comment]
It's not exposed right. But I think we were stuck with the icons and decided to use the sprite file from our server. I asked Raul, Jonas and Holger. Let's see, what they can find out.

**Comment by holgerd** [comment]
Note: "localized_name":"Eisenwarenladen", is needed to avoid app update.

**Comment by holgerd** [comment]
- [ ] @lennerd contacts SMF to discuss icon problem
- [ ]  SMF hopefully can decide on only one way to handle icons, implements it and updates apps.
- [ ] @lennerd removes the old/legacy ways to handle icons in backend

**Comment by lennerd** [comment]
I had a call with @RaphaelHeber to discuss the icon implementation. He will contact me on Friday with some information about the icon implementation in every app. At the moment it looks like every app is using the API as favored. So adding new node types should be no bigger deal.

I also mentioned a solution to have a more stable icon path. At the moment we only send the icon file name which needs some hard coded information in the apps. Using the API metadata section could be good way to send the correct `icon_path` without adding breaking changes. This will also add the possibility to let the apps use a CDN to request icons.

``` json
{
    "conditions": {
        "page": 1,
        "per_page": 200,
        "format": "json",
        "locale": "de"
    },
    "meta": {
        "page": 1,
        "num_pages": 1,
        "item_count_total": 135,
        "item_count": 135,
        "icon_path": "http://assets1.wheelmap.org/icons"
    },
    "node_types": [
        {
            "id": 1,
            "identifier": "bicycle_rental",
            "category_id": 1,
            "category": {
                "id": 1,
                "identifier": "public_transfer"
            },
            "localized_name": "Fahrradvermietung",
            "icon": "cycling.png"
        }
    ]
}
```

I will add this as soon as we added the new node types.

**Comment by holgerd** [comment]
@lennerd any update on this? Did @RaphaelHeber give you feedback?

**Comment by lennerd** [comment]
Yes, he did. There are a few little things we need to change in the Windows and Android App. I need to discuss this with Jonas the next days (maybe friday), to see if we can buy some resources to change the apps.

Windows: Icons are selected but not downloaded from the API. The Windows Phone is using an old ZIP file approach which I want to get rid of.

Android: Icons are not downloaded from the API. I'm not quite sure where the icons are coming from instead, but maybe @RaphaelHeber can add details here.

**Comment by RaphaelHeber** [comment]
I'll talk to Tim and provide more details regarding this topic until Friday.

**Comment by holgerd** [comment]
@RaphaelHeber any updates on this?

**Comment by RaphaelHeber** [comment]
@holgerd I didn't receive feedback from Tim yet - I will definitely get back to you on Friday. I apologize for the delay!

**Comment by holgerd** [comment]
@RaphaelHeber any updates on this?

**Comment by RaphaelHeber** [comment]
Android: The icons have been downloaded from the API once and are hard coded within the app.

**Comment by holgerd** [comment]
Status: Sozialhelden are waiting for SMF to estimate the cost to implement the icon handling in the apps. ("Bitte Aufwand schätzen, dass alle Apps auf die gleiche Art und Weise die Kategorien, Übersetzungen und Icons ohne App-Update von den Servern aus der API ziehen.")

**Comment by holgerd** [comment]
Plan: SMF will update Android App. Result: Only one way all apps get category icons.

**Comment by lennerd** [comment]
I will try to post information about next step for @1000miles today or tomorrow.

**Comment by 1000miles** [comment]
The node-types index page is affected by the error messages of currently removed/missing poi translations, this is why the statistics are shifted and don't appear within the div with 980px width. 

**Image Snapshot on staging server:**

![node_types_missing_translations_17032016](https://cloud.githubusercontent.com/assets/4077916/13848234/2afaae70-ec51-11e5-969d-07bdf91878bc.png)

**On localhost:**

![00000052](https://cloud.githubusercontent.com/assets/4077916/13848273/5d9786dc-ec51-11e5-9919-3cc6081a85c4.png)

**Comment by 1000miles** [comment]
Welcome back! Happy to get input. Ping @lennerd :)

**Comment by holgerd** [comment]
What is the status of this @lennerd ?

**Comment by lennerd** [comment]
Can be closed in favor of #211 and #210 and others to come.

**Comment by holgerd** [comment]
since this refers to the icon list, please leave it open until I tested it all.

**Comment by holgerd** [comment]
btw: I can already see the new node types on https://staging.wheelmap.org/node_types

**Comment by lennerd** [comment]
Yes, but this is not intended. I once tried to have the new node types on Staging, but changes were not merged or completed. The database is still filled with the new node types but without any POIs, as we do not have any sync with the OSM on Staging. A db reset would remove them again.

**Comment by Svenyo** [comment]
@1000miles cc @holgerd The translations are now ready, meaning: most important languages are up to date with 100%:
These are: English (source), German, Russian, French, Spanish, Japanese, Chinese (Taiwan), Swedish. Most other languages have been updated as well, even if they are not ready in the full 100%. Still: please make a full update of all active languages when you implement the node types.

**Comment by 1000miles** [comment]
@holgerd Since this ticket has been created on  4 Nov 2015, I am not so sure about the exact left task here, for example some categories might have been added meanwhile?

Questions:
- As far as I understand my current task finally is to fetch the latest transifex translations for categories and to introduce them into the wheelmap app, is that correct?
- If not, can you please update the initial task list here?

**Comment by holgerd** [comment]
I removed the tasks which are not directly related to this:

- ~~[ ] Suggest a technical solution to show place types which consist of a combination of OSM-tags. Example: *parking=yes AND capacity:disabled=yes*~~
- ~~[ ] Add building=university and treat it like the existing amenity=university~~

**Comment by holgerd** [comment]
@1000miles 
The goal is that the new categories shall be usable in Wheelmap. 

As far as I understand this requires translations and icons, both are missing now on [staging.wheelmap.org/node_types](https://staging.wheelmap.org/node_types).

We prepared translations (in Transifex) and icon-URLs (in the [Google Spreadsheet](https://docs.google.com/spreadsheets/d/12yuBoD8HNaC0sMH3JgLQlImz8NOMcaYgY0kRQpMDlSQ/edit#gid=1897137213)).

What else do you need?

**Comment by holgerd** [comment]
@1000miles Also, I think the OSM-import and export will be affected when we introduce new categories.

**Comment by 1000miles** [comment]
@holgerd 

Thank you for your clean up and task update. Now it is clear. Alright, then I will go ahead with this ticket.

P.S. We discussed it internally here and came to the conclusion that we should introduce the new categories *before* the new production env is going online, this way we can see in advance if and what breaks with the new categories.

**Comment by 1000miles** [comment]
Related PR:

- [ ]  Add new node types for leisure category. #376 - Status: merged, deployed on staging & waiting for @holger's OK to deploy on production
- [ ]  Add new node types to health category. #377 - Status: waiting for rebase by @lennerd 
- [ ]  Add new employment agency node type to goverment category. #378 - Status: waiting for rebase by @lennerd  before merge
- [ ] Add new node types for misc category. #379 - Status: waiting for rebase by @lennerd before merge
- [ ] Add new node types to shopping category. #380 - Status: waiting for rebase by @lennerd before merge

**Comment by 1000miles** [comment]
@holgerd cc @Svenyo & @karolinamakaruk 

The new categories leisure, health, employment agency, misc & shopping are deployed on staging and can be reviewed.

**Comment by karolinamakaruk** [comment]
- I opened https://staging.wheelmap.org/en/nodes/new/name_category, I found new categories but also:

- I expected to see each category once
- Instead I saw some categories twiced, for example Dentist
<img width="713" alt="wheelmap" src="https://cloud.githubusercontent.com/assets/19149119/20672368/5fd19c4a-b581-11e6-8be7-acfaf4575bc4.png">

cc @holgerd

**Comment by lennerd** [comment]
This is the result from a very early try of importing new node types on Staging. This does not appear on master as long as the imports are running through without errors. I'm not 100 % sure what would fix this, but maybe resetting the database completely should fix it.

**Comment by 1000miles** [comment]
Thanks @karolinamakaruk for reporting & @lennerd for short explanation.

So from what we can see now only following categories exist twice when creating new categories as a user:
- dentist
- hearing aid dealer
- psychotherapist
- social facility

@schultyy and me will check and see what is best to fix this.

**Comment by 1000miles** [comment]
@karolinamakaruk cc @lennerd @holgerd 

**Tasks we have done:**
- checked if locally and production also contain duplicates => no, only staging had duplicates in `health` category
- migrated and removed the duplicates (dentist, hearing aid dealer & social facility) from the staging server

Status: **fixed!**

![screen shot 2016-11-29 at 15 08 16](https://cloud.githubusercontent.com/assets/4077916/20712840/21c6759a-b646-11e6-931c-255fc0a9b8be.png)

**Comment by 1000miles** [comment]
Closed. Deployed on production with release: https://github.com/sozialhelden/wheelmap/releases/tag/production-20161129150628.
