### ISSUE TITLE
bring dutch language version online

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#641]

**Comment by anngreenberg** [comment]
@holgerd @Svenyo  
 
Going from past new translations that were included, we have a few open questions for the upcoming to do's: 

- create a map version for dutch: under which address? 
- implement dutch in dropdown menu: under which keyword?
- fetch translations from transifex

**Comment by Svenyo** [comment]
Hi @anngreenberg 

- So, the dutch version should be online with the URL: //wheelmap.org/nl/map
- The Keyword for the dropdown menu is: Nederlands

What kind of input do you need from me concerning Transifex?

**Comment by 1000miles** [comment]
Thanks, @Svenyo .  No further input is required at the moment.

cc @anngreenberg 

**Background:**
As a user I am on wheelmap.org and want to select the `nl` in the language dropdown menu in order to see dutch content.

**Expected paths and redirects:**
http://wheelmap.org/nl > https://wheelmap.org/nl > https://wheelmap.org/nl/map


**#TODO**

- [ ] add `:nl` to config files of [production](https://github.com/sozialhelden/wheelmap/blob/adbddd91e5ef41711facc7f1659732cdea7c7c36/config/environments/production.rb#L87) and [staging](https://github.com/sozialhelden/wheelmap/blob/adbddd91e5ef41711facc7f1659732cdea7c7c36/config/environments/staging.rb#L84)
- [x] create `nl` folder for translation files ([already exists](https://github.com/sozialhelden/wheelmap/tree/master/config/locales/nl))
- [ ] fetch latest translations for `nl` from transifex
- [ ] export i18n js files with `bundle exec rake i18n:js:export`
- [ ] deploy to staging and get approval
- [ ] deploy to production

**Comment by 1000miles** [comment]
@Svenyo 
cc @holgerd @anngreenberg 

We deployed the dutch introduction (PR #647) to staging with [release 20170830084704](https://github.com/sozialhelden/wheelmap/releases/tag/staging-20170830084704) today. It's ready for review and feedback.

**Comment by holgerd** [comment]
I see it is live, closing this issue.
https://wheelmap.org/da/map#/?zoom=14

**Comment by holgerd** [comment]
oops, my bad, it is danish not dutch which is love. ;)

dutch version LGTM:
https://staging.wheelmap.org/nl/map#/?zoom=14

please deploy live.

**Comment by 1000miles** [comment]
Thanks for the feedback, @holgerd . 

cc @Svenyo @anngreenberg 

It's deployed to production with [release 20170906080123](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170906080123) and live now.

### Screens

![00000398](https://user-images.githubusercontent.com/4077916/30101107-66dbc2c0-92eb-11e7-84cf-6bc249632f47.png)

![00000399](https://user-images.githubusercontent.com/4077916/30101141-7e68d16c-92eb-11e7-8166-1174129c6966.png)

**Comment by 1000miles** [comment]
Done. Closing.
