### ISSUE TITLE
Import new pics from Streetspotr spots

### ISSUE THREAD

**Issue by Svenyo** [sozialhelden/wheelmap#651]
So, here are the final CSVs covering POIs and categories from the last part of the campaign.
Can you import the photos according to the workflow and rake task used in https://github.com/sozialhelden/wheelmap/issues/630 ?

[Streetspotr 9_2017.zip](https://github.com/sozialhelden/wheelmap/files/1277588/Streetspotr.9_2017.zip)

**Comment by 1000miles** [comment]
Thanks for the file, @Svenyo . 👍

**Comment by 1000miles** [comment]
# TODO

### 1. Check & import in Development

- [ ] Import  BE_2016.csv
- [ ] Import  DE_2016.csv
- [ ] Import  DK_2016.csv
- [ ] Import  ES_2016.csv
- [ ] Import  FR_2016.csv
- [ ] Import  IR_2016.csv
- [ ] Import   IT_2016.csv
- [ ] Import   NL_2016.csv
- [ ] Import  UK_2016.csv

### 2. Check & import on Staging

- [ ] Import  BE_2016.csv
- [ ] Import  DE_2016.csv
- [ ] Import  DK_2016.csv
- [ ] Import  ES_2016.csv
- [ ] Import  FR_2016.csv
- [ ] Import  IR_2016.csv
- [ ] Import   IT_2016.csv
- [ ] Import   NL_2016.csv
- [ ] Import  UK_2016.csv

### 2. Check & import on Production

- [ ] Import  BE_2016.csv
- [ ] Import  DE_2016.csv
- [ ] Import  DK_2016.csv
- [ ] Import  ES_2016.csv
- [ ] Import  FR_2016.csv
- [ ] Import  IR_2016.csv
- [ ] Import   IT_2016.csv
- [ ] Import   NL_2016.csv
- [ ] Import  UK_2016.csv

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @anngreenberg 

Staging import is done. We imported 9.333 photos on staging with **BE, DE, DK, ES, FR, IR, IT, NL** and **UK** today. We noticed that there were a lot of osm_id that did not exist anymore, please find the stats above for each country.

On monday, 2017-09-11, we will import the same csv on production.

<img width="1233" alt="00000401" src="https://user-images.githubusercontent.com/4077916/30171654-df0ab294-93f2-11e7-8f77-568d547854d8.png">

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @anngreenberg 

Check and import on production is done, please find the updated stats above . According to our import stats only 5 new photos have been imported from the last recent [Streetspotr sept 2017 batch](https://github.com/sozialhelden/wheelmap/issues/651#issue-255282762) which implies most of them have already been imported or the poi could not be found anymore.

```shell
+--------+------------------+------------+---------------------+-------------+--------------+--------------------------------------------------------------------------------------------------------------------+
| id     | image_processing | poi_id     | created_at          | image_width | image_height | source_url                                                                                                         |
+--------+------------------+------------+---------------------+-------------+--------------+--------------------------------------------------------------------------------------------------------------------+
| 124107 |                0 | 2956247446 | 2017-09-11 09:12:54 |        3264 |         2448 | https://download.streetspotr.com/c3dbc8885eb9780f18eee77666f52b3aeb7af405/79f41321e9371c83c85303722b82d3b184eafaa8 |
| 124108 |                0 | 2956247446 | 2017-09-11 09:12:54 |        2448 |         3264 | https://download.streetspotr.com/5e921e868dac49be0cf076e7e5eacf4614f854e8/d761020cb1008ee33bd066fda42fe57d7bdf303a |
| 124109 |                0 | 2956247446 | 2017-09-11 09:12:55 |        2448 |         3264 | https://download.streetspotr.com/67a6f4c3f3f797d4dc1954b2970a48f97d8f1cb0/3aa1a7113514acb762a16276dc68c935164ad178 |
| 124110 |                0 | 3690038250 | 2017-09-11 09:24:31 |        1728 |         2880 | https://download.streetspotr.com/22af7b1e1a45656c3732cdf2d98df3162a5fce08/57c5b4a20d4c9d51e6010bc34e090b295ba61e39 |
| 124111 |                0 | 3690038250 | 2017-09-11 09:24:32 |        2880 |         1728 | https://download.streetspotr.com/d8d5589c2247d886a2dc06be6648127f7400257f/bc5f1364017d60d8bc52f901a99e59f278289538 |
+--------+------------------+------------+---------------------+-------------+--------------+--------------------------------------------------------------------------------------------------------------------+
5 rows in set, 1 warning (0.06 sec)
```

**Comment by Svenyo** [comment]
Hi, are you sure you imported the right set of CSV files? The new files I attached above all had the naming COUNTRYCODE_Final.csv and I wonder why the csv's you've listed are called COUNTRYCODE_2016.csv.

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @anngreenberg

Oh, you are right. I am sorry. I had another Streetspotr folder in the same directory. Will fix this. Thanks for the hint.

**Comment by Svenyo** [comment]
Ok, great! Thanks!

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @anngreenberg 

### Update, Mon Sep 11 17:22:21 CEST 2017

**7494** photos have been imported production today of which **4125** photos still have to go through the carrierwave image processing delayed_job until all photo versions are live. As soon as all of them are finished, we will let you know here.

**Comment by 1000miles** [comment]
@Svenyo cc @holgerd @anngreenberg 

The image processing is done. Please log into the wheelmap admin dashboard if you want to review the images. 

```bash
# mysql> SELECT COUNT(*) FROM photos WHERE user_id = xxxx AND image_processing = 1 AND created_at LIKE "2017-09-11%" ;

+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.04 sec)
```

**Comment by Svenyo** [comment]
Dear @1000miles, thanks, looks fine to me. :-)

**Comment by anngreenberg** [comment]
Thank you for checking, @Svenyo. 
Import done, therefore closing.
