### ISSUE TITLE
Widget not working on SSL pages

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#93]
Buge report we got from somebody trying to use our widget:

====

Hi there,

We have problems implementing the Wheelmap widget on https://dev.handiscover.com
It worked well when running on localhost, but we can't manage to get it running on the https site. If we load the iframe by the original url (http), the browser refuse to load it because of mixed content. Replacing the url with https doesn't work either, as it is 304 redirected to the http version.
We have both tried to load the widget with JavaScript and generated it in the html source, but no luck.

The source code we use is like this:
<iframe src="http://wheelmap.org/sv/embed/FvjdVcWsokKopF62RSmy/?lat=43.4803174&amp;lon=-1.5625447&amp;zoom=15" border="0" height="440" width="100%"></iframe>

Best regards, Lukas Mattsson, Handiscover

**Comment by Xylakant** [comment]
do we provide the widget via HTTPS? Plain HTTP Content is usually forbidden by the mixed content policies.

**Comment by lennerd** [comment]
Yes, rights, we are aware of this problem. And it already happens with some of our users.

I have no big expierence in adding an HTTPS protocol. But I think it should be no big deel to add it to our servers. In the application should be no changes needed.

**Comment by Xylakant** [comment]
there's some stuff that might need to be done if we want to provide a proper user experience. HTST headers, links for transactional emails might need adjusting, some redirects might need work. We need to ensure we're not embedding scripts and CSS from non-https sources. Cloudflare etc,

First of all we need a certificate, and we certainly need some testing.

**Comment by lennerd** [comment]
Good point about the assets. As far as I know, the only external assets we use are some analytics and social badgets. But they all should work fine with HTTPS. We still need to check this though.

> First of all we need a certificate, and we certainly need some testing.

I think the best way would be to first add SSL only to the staging server (if possible). So we can check every page and redirect and give the team the chance to go to every corner of the page.

**Comment by thermann78** [comment]
Cloudflare should handle SSL without any problems, it's just a matter of settings. Let me know if some parts are switched to HTTPS so I just do the setup change on CF.

**Comment by holgerd** [comment]
Let's collect concrete tasks for this issue.

**Comment by Xylakant** [comment]
SSL is enabled for stage using a self-signed cert. A quick test shows that we're loading resources from plain http which breaks the site. The following tasks have been opened to track progress on the ticket:

- [ ] Create a wildcard certificate for wheelmap.org [#132]
- [ ] Enable TLS for community.wheelmap.org [#133]
- [ ] Enable TLS on Cloudflare [#134]
- [ ] Ensure that the widget loads resources from protocol relative URLs (or https) [#135]

**Comment by thermann78** [comment]
Issue #134 : done.

**Comment by lennerd** [comment]
The widget generator is also using a relative protocol in the embed code now.

**Comment by holgerd** [comment]
@lennerd that means the widget is ready for SSL, yes?

**Comment by lennerd** [comment]
The current branch for the SSL asset changes is not merged into master. @Xylakant wanted to contact me when he had time to change the server settings to pass the currently used protocole. Otherwise rails will not be able to generate the correct asset host.

When this is done, I would rebase to master and deploy this changes to staging.

**Comment by holgerd** [comment]
ping @Xylakant

**Comment by Xylakant** [comment]
I deployed a test config on prod, please try. We still need to do some cloudflare configuration to make this fully secure, currently only the connection between the browser and cloudflare is encrypted, not the connection between cloudflare and the origin server.

**Comment by holgerd** [comment]
@Xylakant can you do the cloudflare stuff? Would greatly reduce communication problems between all of us I think :)

**Comment by Xylakant** [comment]
@holgerd I don't have access to the CF account.

**Comment by holgerd** [comment]
@Xylakant the cloudflare login is here: https://socialheroes.1password.com/ (you and thuy should have access to this vault)

**Comment by holgerd** [comment]
@Xylakant  When do you plan to work on this?

**Comment by holgerd** [comment]
@lennerd Can I assign this to you? Felix told me his config is not blocking this issue. It would be great if we could deliver this tomorrow so handiscover can start its campaign,

**Comment by holgerd** [comment]
As discussed with @lennerd and @Xylakant this is fixed and can be closed.

**Comment by lennerd** [comment]
FYI: http://codepen.io/lennerd/pen/JXxadY
